name: ch arm

on:
  repository_dispatch:
  workflow_dispatch:

env:
  REPO_BRANCH: v25.3.6.56-lts

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Initialization environment
        run: |
          sudo -E apt-get -qq update
          sudo -E  apt-get install git cmake ccache python3 ninja-build nasm yasm gawk lsb-release wget software-properties-common gnupg
          sudo -E apt-get -qq clean
          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
          echo $PWD

      - name: Clone source code
        run: |
          df -hT $PWD
          echo $PWD
          git clone https://github.com/ClickHouse/ClickHouse.git -b $REPO_BRANCH ch
          cd ch
          git submodule update --init --jobs 12

      - name: build
        id: build
        env:
          CC: clang-19
          CXX: clang++-19
        run: |
          cd ch
          ls -la
          mkdir -p build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=../cmake/linux/toolchain-aarch64.cmake -DNO_ARMV81_OR_HIGHER=1 -DENABLE_RUST=OFF
          echo "Build directory contents after cmake:"
          ls -la
          ninja

      - name: Upload files
        uses: actions/upload-artifact@main
        with:
          name: ClickHouse-$REPO_BRANCH
          path:  $GITHUB_WORKSPACE/ch/build